---
gateway:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /
            pathType: Prefix
loki:
  commonConfig:
    replication_factor: 1
  useTestSchema: true
  storage:
    # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
    # Please provide these values if you are using object storage.
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
monitoring:
  lokiCanary:
    enabled: false
test:
  enabled: false
